### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by ltb801** [aipal-nchu/RiceShootCounting#2]
Hi, 

I would like to ask if you could provide a working download link for the dataset? The current links are not working. 

Thank you very much!

**Comment by CloudTseng** [comment]
Hi,

Sorry for the data access issue.

The cloud storage we used was ended due to the end of our previous project. We're moving the data to the [platform](https://aidata.nchu.edu.tw/smarter/) hosted in our campus. It still takes some time to put all the data on the platform (need to fill some documents like FAIR...).

Still thanks for accessing the dataset.

**Comment by ltb801** [comment]
Thanks for your help!
